version: '3.1'

services:
  productsrv:
    build: product/.
    image: brunopenso/istiodemo_product
    container_name: istiodemo_product
    ports:
      - "3001:3001"
    environment:
      - 'APPLICATION_PORT=3001'
      - 'DETAIL_SERVICE_PORT=3002'
      - 'DETAIL_HOSTNAME=productdetailsrv'
    networks: 
      - network
  productdetailsrv:
    build: productDetails/.
    image: brunopenso/istiodemo_productdetail
    container_name: istiodemo_productdetail
    ports:
      - "3002:3002"
    environment:
      - 'APPLICATION_PORT=3002'
    networks: 
      - network
networks:
  network:
    driver: bridge